### ISSUE TITLE
3.7.10 database still does not work

### ISSUE THREAD

**Issue by Ardy000** [alexal1/Insomniac#332] opened 2021-05-05 16:23 UTC
It says successful migration completed, but when doing unfollow followed by bot, the bot does not unfollow anyone thinking it has following status none so im assuming it will also reinteract with already interacted people too

**Comment by alexal1** [comment] 2021-05-05 17:47
It works completely correct as of `v3.7.11`, but older versions weren't writing to the database that profile was followed by the bot itself. Sorry for this issue. You can run unfollowing with `--unfollow-followed-by-anyone` and use whitelist.

**Comment by alexal1** [comment] 2021-05-05 17:48
Also duplicate of #319

**Closed by alexal1** 2021-05-05 17:47 UTC
