### ISSUE TITLE
Switching did not work FollowersFollowingListView *(BUG)

### ISSUE THREAD

**Issue by rusellned** [alexal1/Insomniac#355] opened 2021-06-23 00:55 UTC
Hello, switching between tabs did not work when I had common friends. I Changed the values in "textContains" "Followers" "Following" to small letters. 

It seems to me that the tab switch has not worked for a couple of weeks after the instagram update, because if you did not have mutual friends, subscribers were opened by default.

**Comment by alexal1** [comment] 2021-06-23 10:26
Thanks!

**Comment by alexal1** [comment] 2021-06-23 10:26
Duplicate of #353

**Closed by alexal1** 2021-06-23 10:26 UTC
