### ISSUE TITLE
Bug with video posts, not only with IGTV

### ISSUE THREAD

**Issue by xerZV** [alexal1/Insomniac#9] opened 2020-06-10 06:30 UTC
Hello @alexal1 .
I noticed some strange behavior with some video posts. 
It opens the video post then sleep for some seconds and before the double tap stack trace below
```
Sleep for 4 seconds
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/uiautomator/__init__.py", line 438, in wrapper
    return _method_obj(*args, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/uiautomator/__init__.py", line 127, in __call__
    result = urllib2.urlopen(req, timeout=self.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insomniac.py", line 90, in _job_handle_bloggers
    handle_blogger(device, blogger, likes_count, storage, _on_like, on_interaction)
  File "/home/pi/workspace/insomniac/action_handle_blogger.py", line 18, in handle_blogger
    _iterate_over_followers(device, interaction, storage, on_interaction)
  File "/home/pi/workspace/insomniac/action_handle_blogger.py", line 69, in _iterate_over_followers
    interaction_succeed = interaction(device)
  File "/home/pi/workspace/insomniac/action_handle_blogger.py", line 114, in _interact_with_user
    if not _open_photo_and_like(device, row, column, on_like):
  File "/home/pi/workspace/insomniac/action_handle_blogger.py", line 148, in _open_photo_and_like
    action_bar_bottom = action_bar.bounds['bottom']
  File "/home/pi/.local/lib/python3.5/site-packages/uiautomator/__init__.py", line 934, in __getattr__
    info = self.info
  File "/home/pi/.local/lib/python3.5/site-packages/uiautomator/__init__.py", line 945, in info
    return self.jsonrpc.objInfo(self.selector)
  File "/home/pi/.local/lib/python3.5/site-packages/uiautomator/__init__.py", line 443, in wrapper
    return _JsonRPCMethod(url, method, timeout, False)(*args, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/uiautomator/__init__.py", line 438, in wrapper
    return _method_obj(*args, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/uiautomator/__init__.py", line 127, in __call__
    result = urllib2.urlopen(req, timeout=self.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```

**Comment by alexal1** [comment] 2020-06-11 07:10
Are you sure that the problem is with video posts, not with adb connection? Because `socket.timeout: timed out` simply says that device didn't answer after a command was sent to it. Please check https://github.com/alexal1/Insomniac/issues/14#issuecomment-642451673. I will close this now, feel free to reopen if I'm wrong.

**Closed by alexal1** 2020-06-11 07:10 UTC
