### ISSUE TITLE
fail safe function help !?

### ISSUE THREAD

**Issue by potentowl** [alexal1/Insomniac#86] opened 2020-08-20 11:41 UTC
##PROBLEM
get message`"Need to scroll now"` when b0t can scroll no further,,,

come back and it has been trying to scroll for hours instead of interact with next username.

##SOLUTION
**code located at line 144, in action_handle_blogger.py**
how to make function so if `"Need to scroll now"` is printed 5 times consecutively than instead of being stuck in a loop and not scrolling the b0t interacts with the next username available.

**Comment by potentowl** [comment] 2020-08-24 02:08
Problem **It can't scroll because it scrolled too much**
Solution **Identify each mistake with number : if mistake number > 20 than interact with next username**
**My pseudo-code**
LINE 12: `counter = 0`
LINE 13: `counter1 = [0,0]`
LINE 124:             ```
else:
                counter1[0] += 1 #total counter
                counter1[1] += 1 #concurrent hits
                print("Miss_#{}".format(counter1[0]))
```
LINE 152:         ```
elif screen_iterated_followers > 0:
            counter1[1] = 0 #concurrent reset to 0 when else is triggered
            counter += 1
            print("Hit_#{}".format(counter))
```

**Comment by alexal1** [comment] 2020-08-24 11:39
> Identify each mistake with number : if mistake number > 20 than interact with next username

What if I want to interact with someone's followers, but I already interacted with say 100 of them earlier? Then your solution won't let me do it.

Actually I meant device's screenshot. I don't understand why it goes into a loop, that doesn't happen for me.

**Comment by potentowl** [comment] 2020-08-25 21:48
If you already interacted with 100 users earlier than it would stop after 20 mistakes and move to next username,,, if there is no other username than the script stops. i dont know how to code that into script so i just giving idea to improve smoothness of b0t because, also say your interactions -- set at 100, and most of the accounts are private so it keeps trying to interact and is stuck in loop because it can never reach 100 interactions because it scrolls too much and never reaches 100 interactions.

**Comment by alexal1** [comment] 2020-08-26 19:08
> If you already interacted with 100 users earlier than it would stop after 20 mistakes and move to next username

Well this behavior is not expected by most users, I don't want to do it this way...

> Scroll limit

Do you mean a loop? When after long scrolling you start to see the same users as before?
Seems it's a duplicate of #78

**Comment by alexal1** [comment] 2020-09-01 08:56
Please try on `v2.0.5` and reopen if it's not what you've expected

**Closed by alexal1** 2020-09-01 08:56 UTC
