### ISSUE TITLE
Only mutual followers are being interacted with - No followers were iterated, finish.

### ISSUE THREAD

**Issue by skiwlkr** [alexal1/Insomniac#347] opened 2021-06-17 11:11 UTC
I'm having a weird issue lately.
Insomiac is doing no more interaction of my target accounts.
I watched Insomiac on my Android instance and realized that its only looking at the mutual followers, which are processed quickly in one session.

Insomniac opens the Accounts followers but is only looking at the mutual followers and not overall followers of the account, so quickly runs out of Accounts to interact with.
If I'm manually clicking on the Followers Tab, insomiac is seeing all the not interacted accounts and starts it's job. 
Seems like the Click is missing, or it needs a small delay..?

Why is this happening? Thanks!
I'm running the latest version 3.7.12

**Comment by simonmannsfeld** [comment] 2021-06-17 21:42
This issue seems to be for every user of insomniac. It's caused by an update of the Instagram app's UI. I guess it will be fixed soon! ☝️

**Comment by skiwlkr** [comment] 2021-06-18 11:09
Thanks for clearing this up Simon!
Looking forward to the update

**Comment by MelBourbon** [comment] 2021-06-18 15:03
This affects currently also the "unfollow-non-followers" function as only mutual followers are checked and this leads to unfollow people who are still following you.

**Comment by simonmannsfeld** [comment] 2021-06-19 19:04
I created a pull request #349. It should solve the problem. It's just a little change. Let's hope it will be merged soon. 🥳

**Comment by skiwlkr** [comment] 2021-06-20 20:21
Thanks @simonmannsfeld!
I just pulled the 3.7.13 and tried to run it, unfortunately it crashed right away

`Cannot get module actions_impl from v3.7.13: 403 (Forbidden)`

The log says theres a new version availabe (3.7.14). But all I can see on git is 3.7.13

**Comment by edukessen** [comment] 2021-06-21 15:02
> Thanks @simonmannsfeld!
> I just pulled the 3.7.13 and tried to run it, unfortunately it crashed right away
> 
> `Cannot get module actions_impl from v3.7.13: 403 (Forbidden)`
> 
> The log says theres a new version availabe (3.7.14). But all I can see on git is 3.7.13

Any updates to this? I try updating via pip too but only get stuck on 3.7.13. I get the same crash/error.

**Comment by alexal1** [comment] 2021-06-21 16:56
Fixed in `v3.7.14`

**Closed by alexal1** 2021-06-21 16:56 UTC
