### ISSUE TITLE
scrollToEnd  throws Error

### ISSUE THREAD

**Issue by shippie** [alexal1/Insomniac#345] opened 2021-06-15 12:14 UTC
uiautomator2.exceptions.UiObjectNotFoundError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=androidx.recyclerview.widget.RecyclerView, RESOURCE_ID=com.instagram.android:id/recycler_view], method: scrollToEnd

[Crash-2021-06-15-07-56-20.zip](https://github.com/alexal1/Insomniac/files/6655479/Crash-2021-06-15-07-56-20.zip)

**Comment by alexal1** [comment] 2021-06-21 19:32
Duplicate of #344

**Closed by alexal1** 2021-06-21 19:32 UTC
